version: '3.8'

services:
  orbitapostgres:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: orbita
      POSTGRES_PASSWORD: orbita
      POSTGRES_DB: orbita
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  orbitaredis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
